/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Backend.Arbol;
import Backend.Dato;
import Backend.Grafos.Grafos;
import Backend.Grafos.Vertice;
import Backend.ListaEnlazada.ListaEnlazadaDobleC;
import Backend.Recorrido;
import java.awt.Desktop;
import java.awt.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author astridmc
 */
public class Ventana1 extends javax.swing.JPanel {

    ListaEnlazadaDobleC<Recorrido> listaRecorridosFab= new ListaEnlazadaDobleC();
    Grafos grafo = new Grafos();
    public static String medio = null;
    ArrayList<Dato> datos = null;
    ArrayList<Recorrido> recorrido;
     Recorrido favorito;
    /**
     * Creates new form Ventana1
     *
     * @param datos1
     */
    public Ventana1(ArrayList<Dato> datos1) {
        initComponents();
        datos = datos1;
        panelIrRutas.setVisible(false);

        LlenarMedio();
        grafo.InsertarVertices(datos, medio);
        LlenarLugares();
        insertarImagen(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboOrigen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ComboOrigen = new javax.swing.JComboBox<>();
        btnBuscarRutas = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        ComboAPie = new javax.swing.JComboBox<>();
        ComboDestino3 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        tipoTransporte = new javax.swing.JLabel();
        imagTransporte = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        panelIrRutas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mejorRuta = new javax.swing.JLabel();
        comboDestino = new javax.swing.JComboBox<>();
        btnIr = new javax.swing.JButton();
        puntosRuta = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblDist = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        idFav = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        imagenPanel = new javax.swing.JPanel();
        arbolPanel = new javax.swing.JPanel();
        guardaImagen = new javax.swing.JButton();

        setBackground(new java.awt.Color(202, 230, 253));

        comboOrigen.setBackground(new java.awt.Color(1, 60, 66));
        comboOrigen.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(254, 254, 254), new java.awt.Color(254, 254, 254)));
        comboOrigen.setForeground(new java.awt.Color(254, 254, 254));

        jLabel1.setFont(new java.awt.Font("URW Chancery L", 1, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Escoja el Origen:");

        jLabel2.setFont(new java.awt.Font("URW Chancery L", 1, 27)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Escoja el Destino:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setAlignmentY(1.0F);

        ComboOrigen.setFont(new java.awt.Font("URW Bookman L", 3, 20)); // NOI18N
        ComboOrigen.setForeground(new java.awt.Color(1, 1, 1));
        ComboOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboOrigenActionPerformed(evt);
            }
        });

        btnBuscarRutas.setFont(new java.awt.Font("URW Bookman L", 3, 18)); // NOI18N
        btnBuscarRutas.setForeground(new java.awt.Color(0, 132, 111));
        btnBuscarRutas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Imagenes/RutasPopulares.png"))); // NOI18N
        btnBuscarRutas.setText("BUSCAR RUTAS");
        btnBuscarRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRutasActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("URW Chancery L", 1, 27)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Buscar Rutas en Base A:");

        ComboAPie.setFont(new java.awt.Font("URW Bookman L", 3, 20)); // NOI18N
        ComboAPie.setForeground(new java.awt.Color(1, 1, 1));
        ComboAPie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboAPieActionPerformed(evt);
            }
        });

        ComboDestino3.setFont(new java.awt.Font("URW Bookman L", 3, 20)); // NOI18N
        ComboDestino3.setForeground(new java.awt.Color(1, 1, 1));
        ComboDestino3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboDestino3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboDestino3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout comboOrigenLayout = new javax.swing.GroupLayout(comboOrigen);
        comboOrigen.setLayout(comboOrigenLayout);
        comboOrigenLayout.setHorizontalGroup(
            comboOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comboOrigenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(comboOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comboOrigenLayout.createSequentialGroup()
                        .addGroup(comboOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(comboOrigenLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comboOrigenLayout.createSequentialGroup()
                                .addComponent(ComboOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(comboOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(comboOrigenLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                                .addComponent(ComboDestino3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))
                            .addGroup(comboOrigenLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(comboOrigenLayout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(ComboAPie, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarRutas, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(comboOrigenLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator2)
        );
        comboOrigenLayout.setVerticalGroup(
            comboOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comboOrigenLayout.createSequentialGroup()
                .addGroup(comboOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(comboOrigenLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comboOrigenLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ComboDestino3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(comboOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comboOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addComponent(btnBuscarRutas))
                    .addComponent(ComboAPie, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        jPanel4.setBackground(new java.awt.Color(18, 55, 71));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tipoTransporte.setFont(new java.awt.Font("URW Chancery L", 3, 30)); // NOI18N
        tipoTransporte.setForeground(new java.awt.Color(254, 254, 254));
        tipoTransporte.setText("TRANSPORTE");

        imagTransporte.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tipoTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imagTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(imagTransporte, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(tipoTransporte, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)))
        );

        jPanel5.setBackground(new java.awt.Color(68, 232, 187));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.black));

        panelIrRutas.setBackground(new java.awt.Color(68, 232, 187));
        panelIrRutas.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, null));

        jLabel3.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(1, 1, 1));
        jLabel3.setText("La Mejor Ruta Es:");

        jLabel4.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(22, 0, 0));
        jLabel4.setText("Las Rutas posibles son:");

        mejorRuta.setFont(new java.awt.Font("URW Bookman L", 1, 18)); // NOI18N
        mejorRuta.setForeground(new java.awt.Color(132, 0, 0));
        mejorRuta.setText("Mejor Ruta");

        comboDestino.setFont(new java.awt.Font("URW Bookman L", 3, 20)); // NOI18N
        comboDestino.setForeground(new java.awt.Color(1, 1, 1));
        comboDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboDestino.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboDestinoItemStateChanged(evt);
            }
        });
        comboDestino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboDestinoMouseClicked(evt);
            }
        });
        comboDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDestinoActionPerformed(evt);
            }
        });

        btnIr.setFont(new java.awt.Font("URW Bookman L", 3, 18)); // NOI18N
        btnIr.setForeground(new java.awt.Color(0, 132, 111));
        btnIr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Imagenes/localizar.png"))); // NOI18N
        btnIr.setText("  Ir");
        btnIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrActionPerformed(evt);
            }
        });

        puntosRuta.setFont(new java.awt.Font("URW Bookman L", 3, 20)); // NOI18N
        puntosRuta.setForeground(new java.awt.Color(1, 1, 1));
        puntosRuta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setFont(new java.awt.Font("URW Bookman L", 0, 16)); // NOI18N
        jLabel8.setText("Escoja el punto al que  ");

        jLabel9.setFont(new java.awt.Font("URW Bookman L", 0, 16)); // NOI18N
        jLabel9.setText("se mueve");

        jLabel10.setFont(new java.awt.Font("URW Bookman L", 0, 16)); // NOI18N
        jLabel10.setText("Distancia de ruta:");

        lblDist.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        lblDist.setForeground(new java.awt.Color(22, 0, 0));
        lblDist.setText("00");

        jLabel11.setFont(new java.awt.Font("URW Bookman L", 0, 16)); // NOI18N
        jLabel11.setText("Ruta Favorita:");

        idFav.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        idFav.setForeground(new java.awt.Color(22, 0, 0));
        idFav.setText("id");

        javax.swing.GroupLayout panelIrRutasLayout = new javax.swing.GroupLayout(panelIrRutas);
        panelIrRutas.setLayout(panelIrRutasLayout);
        panelIrRutasLayout.setHorizontalGroup(
            panelIrRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIrRutasLayout.createSequentialGroup()
                .addGroup(panelIrRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIrRutasLayout.createSequentialGroup()
                        .addGroup(panelIrRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelIrRutasLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelIrRutasLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(puntosRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIrRutasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mejorRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(panelIrRutasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIrRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIrRutasLayout.createSequentialGroup()
                        .addComponent(btnIr, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelIrRutasLayout.createSequentialGroup()
                        .addGroup(panelIrRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelIrRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(panelIrRutasLayout.createSequentialGroup()
                .addGroup(panelIrRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIrRutasLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDist, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelIrRutasLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(idFav, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelIrRutasLayout.setVerticalGroup(
            panelIrRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIrRutasLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mejorRuta)
                .addGap(1, 1, 1)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIrRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDist, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(panelIrRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idFav, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(puntosRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIr))
        );

        btnIr.getAccessibleContext().setAccessibleName("IR");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelIrRutas, javax.swing.GroupLayout.PREFERRED_SIZE, 237, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelIrRutas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(191, 15, 11));
        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(254, 254, 254));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        imagenPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.black));
        imagenPanel.setMinimumSize(new java.awt.Dimension(50, 50));
        imagenPanel.setOpaque(false);
        imagenPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                imagenPanelComponentResized(evt);
            }
        });

        javax.swing.GroupLayout imagenPanelLayout = new javax.swing.GroupLayout(imagenPanel);
        imagenPanel.setLayout(imagenPanelLayout);
        imagenPanelLayout.setHorizontalGroup(
            imagenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        imagenPanelLayout.setVerticalGroup(
            imagenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("RUTAS", imagenPanel);

        javax.swing.GroupLayout arbolPanelLayout = new javax.swing.GroupLayout(arbolPanel);
        arbolPanel.setLayout(arbolPanelLayout);
        arbolPanelLayout.setHorizontalGroup(
            arbolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );
        arbolPanelLayout.setVerticalGroup(
            arbolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("ARBOL", arbolPanel);

        guardaImagen.setFont(new java.awt.Font("URW Bookman L", 3, 18)); // NOI18N
        guardaImagen.setForeground(new java.awt.Color(0, 132, 111));
        guardaImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Imagenes/2.png"))); // NOI18N
        guardaImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardaImagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(comboOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardaImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(33, 33, 33)
                        .addComponent(guardaImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ComboOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboOrigenActionPerformed
    ArrayList<Recorrido> miRecorrido = new ArrayList();
    private void btnBuscarRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRutasActionPerformed
        Arbol arbol = new Arbol();
        ArrayList<Recorrido> recorr = new ArrayList();
        ArrayList<Recorrido> recorridoDes = new ArrayList();
        Vertice verticeOrigen = grafo.getVertices().get(ComboOrigen.getSelectedIndex());
        Vertice verticeDestino = grafo.getVertices().get(ComboDestino3.getSelectedIndex());
        if ("A Pie".equals(medio)) {
            int opcion = ComboAPie.getSelectedIndex();
            grafo.setCaminosRecorridos();
            grafo.CrearRecorridos(verticeOrigen, verticeDestino);
            recorridoDes = grafo.CalcularMenorRecorrido(opcion, false);
            recorr = grafo.ordenarRecorridos(recorridoDes);
            arbol.cerearArbol(grafo.CalcularMenorRecorrido(opcion, false));
            llenarRtuas(arbol, recorr);
        } else {
            int opcion = ComboAPie.getSelectedIndex();
            grafo.setCaminosRecorridos();
            grafo.CrearRecorridos(verticeOrigen, verticeDestino);
            recorridoDes = grafo.CalcularMenorRecorrido(opcion, false);
            recorr = grafo.ordenarRecorridos(recorridoDes);
            arbol.cerearArbol(grafo.CalcularMenorRecorrido(opcion, true));
            llenarRtuas(arbol, recorr);
        }
        if ("A Pie".equals(medio)) {
            //System.out.println("grafo no dirigido ");
            grafo.CrearImagenGrafoNODirigidoRECORRIDO(recorr);
        } else {
            grafo.CrearImagenGrafoDirigidoPrincipalRECORRIDO(recorr);
        }
        miRecorrido= recorr;
        favorito = listaRecorridosFab.ObtenerCaminoFavorito(listaRecorridosFab,verticeOrigen.getNombre(), verticeDestino.getNombre());
        if(favorito!=null){
            idFav.setText(String.valueOf(favorito.getId()));
        }else{
            idFav.setText("sin Fav");
        }
        //arbol.crearDotArbol(recorr);
        arbol.creadorArbol(arbol.CrearDotArbol(arbol.getRaiz()));
        panelIrRutas.setVisible(true);
        insertarImagen(true);
    }//GEN-LAST:event_btnBuscarRutasActionPerformed

    private void btnIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrActionPerformed
        //Vertice final1 = grafo.getVertices().get(grafo.ObtenerIndiceVertice(ComboDestino3.getSelectedItem().toString()));
        ingresarCaminos(miRecorrido.get(ComboAPie.getSelectedIndex()));
        Vertice verticeOrigen = grafo.getVertices().get(buscarIndice(grafo.getVertices(), puntosRuta.getSelectedItem().toString()));
        System.out.println(" BUSCANDO--------" + verticeOrigen.getNombre());
        Arbol arbol = new Arbol();
        ArrayList<Recorrido> recorr = new ArrayList();
        ArrayList<Recorrido> recorridoDes = new ArrayList();
        Vertice verticeDestino = grafo.getVertices().get(ComboDestino3.getSelectedIndex());
        if ("A Pie".equals(medio)) {
            int opcion = ComboAPie.getSelectedIndex();
            grafo.setCaminosRecorridos();
            grafo.CrearRecorridos(verticeOrigen, verticeDestino);
            recorridoDes = grafo.CalcularMenorRecorrido(opcion, false);
            recorr = grafo.ordenarRecorridos(recorridoDes);
            arbol.eliminarDatosArbol(arbol.getRaiz());
            arbol.cerearArbol(grafo.CalcularMenorRecorrido(opcion, false));
            llenarRtuas(arbol, recorr);
        } else {
            int opcion = ComboAPie.getSelectedIndex();
            grafo.setCaminosRecorridos();
            grafo.CrearRecorridos(verticeOrigen, verticeDestino);
            recorridoDes = grafo.CalcularMenorRecorrido(opcion, false);
            recorr = grafo.ordenarRecorridos(recorridoDes);
            arbol.eliminarDatosArbol(arbol.getRaiz());
            arbol.cerearArbol(grafo.CalcularMenorRecorrido(opcion, true));
            llenarRtuas(arbol, recorr);
        }
        miRecorrido= recorr;

        if ("A Pie".equals(medio)) {
            //System.out.println("grafo no dirigido ");
            grafo.CrearImagenGrafoNODirigidoRECORRIDO(recorr);
        } else {
            grafo.CrearImagenGrafoDirigidoPrincipalRECORRIDO(recorr);
        }
        
        favorito = listaRecorridosFab.ObtenerCaminoFavorito(listaRecorridosFab,verticeOrigen.getNombre(), verticeDestino.getNombre());
        if(favorito!=null){
            idFav.setText(String.valueOf(favorito.getId()));
        }else{
            idFav.setText("sin Fav");
        }
        arbol.creadorArbol(arbol.CrearDotArbol(arbol.getRaiz()));
        //arbol.crearDotArbol(recorr);
        panelIrRutas.setVisible(true);
        insertarImagen(false);


    }//GEN-LAST:event_btnIrActionPerformed

    private void ComboAPieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboAPieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboAPieActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDestinoActionPerformed

    private void imagenPanelComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_imagenPanelComponentResized
        try {
            if (imagenPanel.getComponents().length > 0) {
                imagen.setBounds(0, 0, imagenPanel.getWidth(), imagenPanel.getHeight());
                imagen.setIcon(new ImageIcon(portada.getImage().getScaledInstance(imagenPanel.getWidth(), imagenPanel.getHeight(), Image.SCALE_SMOOTH)));
                imagenPanel.remove(0);
                imagenPanel.add(imagen);
                //System.out.println(imagenPanel.getComponent(0).getName());
            }
            if (arbolPanel.getComponents().length > 0) {
                imagenArbol.setBounds(0, 0, arbolPanel.getWidth(), arbolPanel.getHeight());
                imagenArbol.setIcon(new ImageIcon(arbolPortada.getImage().getScaledInstance(arbolPanel.getWidth(), arbolPanel.getHeight(), Image.SCALE_SMOOTH)));
                arbolPanel.remove(0);
                arbolPanel.add(imagenArbol);
                //System.out.println(imagenPanel.getComponent(0).getName());
            }

            
        } catch (Exception e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_imagenPanelComponentResized

    private void comboDestinoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboDestinoItemStateChanged

    }//GEN-LAST:event_comboDestinoItemStateChanged

    private void ComboDestino3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboDestino3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboDestino3ActionPerformed

    private void comboDestinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboDestinoMouseClicked
        LlenarPuntosRuta();
    }//GEN-LAST:event_comboDestinoMouseClicked

    private void guardaImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardaImagenActionPerformed
        JFileChooser guardar = new JFileChooser();
        guardar.showSaveDialog(null);
        guardar.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        File IMAGEN = new File(fondo);
        File archivo = guardar.getSelectedFile();
        if (IMAGEN.exists()) {
            try {
                Files.copy(Paths.get(IMAGEN.getAbsolutePath()), Paths.get(archivo.getAbsolutePath()), StandardCopyOption.REPLACE_EXISTING);
            } catch (IOException ex) {
                Logger.getLogger(Ventana1.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        } else {
            System.out.println("El fichero " + "grafo" + " no existe en el directorio ");
        }
        
        try {
                File path = new File(fondo);
                Desktop.getDesktop().open(path);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
    }//GEN-LAST:event_guardaImagenActionPerformed
    String fondo = "grafo.png";
    String arbolIM = "arbol.png";
    JLabel imagen = new JLabel();
    JLabel imagenArbol = new JLabel();
    ImageIcon portada;
    ImageIcon arbolPortada;

    public void insertarImagen(boolean arbol) {
        try {
            if (arbol) {
                arbolPortada = new ImageIcon(arbolIM);
                arbolPanel.setVisible(false);
                imagenArbol.setBounds(0, 0, arbolPanel.getWidth(), arbolPanel.getHeight());
                if (arbolPanel.getWidth() > 0 && arbolPanel.getHeight() > 0) {
                    //System.out.println("ooooooo");
                    imagenArbol.setIcon(new ImageIcon(arbolPortada.getImage().getScaledInstance(arbolPanel.getWidth(), arbolPanel.getHeight(), Image.SCALE_SMOOTH)));
                } else {
                    imagenArbol.setIcon(new ImageIcon(arbolPortada.getImage().getScaledInstance(3276, 3276, Image.SCALE_SMOOTH)));
                }
                arbolPanel.add(imagenArbol);
                arbolPanel.repaint();
                //System.out.println("pintadoooo");
                arbolPanel.setVisible(true);
            }
            portada = new ImageIcon(fondo);
            imagenPanel.setVisible(false);
            imagen.setBounds(0, 0, imagenPanel.getWidth(), imagenPanel.getHeight());
            if (imagenPanel.getWidth() > 0 && imagenPanel.getHeight() > 0) {
                //System.out.println("ooooooo");
                imagen.setIcon(new ImageIcon(portada.getImage().getScaledInstance(imagenPanel.getWidth(), imagenPanel.getHeight(), Image.SCALE_SMOOTH)));
            } else {
                imagen.setIcon(new ImageIcon(portada.getImage().getScaledInstance(3276, 3276, Image.SCALE_SMOOTH)));
            }
            imagenPanel.add(imagen);
            imagenPanel.repaint();
            //System.out.println("pintadoooo");
            imagenPanel.setVisible(true);
        } catch (Exception e) {
            System.out.println(e + "errrr");
        }

    }

    public void LlenarLugares() {
        ArrayList<String> uno = new ArrayList();
        ArrayList<String> dos = new ArrayList();

        ComboOrigen.removeAllItems();
        ComboDestino3.removeAllItems();
        for (int i = 0; i < grafo.getVertices().size(); i++) {
            String id = Integer.toString(grafo.getVertices().get(i).getId());
            if (contiene(uno, grafo.getVertices().get(i).getNombre())) {
                ComboOrigen.addItem(grafo.getVertices().get(i).getNombre());
            }
            if (contiene(dos, grafo.getVertices().get(i).getNombre())) {
                ComboDestino3.addItem(grafo.getVertices().get(i).getNombre());
            }

        }

    }

    public boolean contiene(ArrayList<String> caminos2, String vertice) {

        for (int i = 0; i < caminos2.size(); i++) {
            if (caminos2.get(i).toLowerCase() == vertice.toLowerCase()) {
                //  System.out.println("COMPARANDO........."+caminos2.get(i).getNombre()+" = "+vertice.getNombre());
                return false;
            }
        }
        return true;
    }

    public void LlenarMedio() {
        if (medio != null) {
            tipoTransporte.setText(medio);
            if (!"A Pie".equals(medio)) {
                ComboAPie.setVisible(true);
                ImageIcon piee = new ImageIcon("peaton2.png");
                imagTransporte.setIcon(new ImageIcon(piee.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH)));
                ComboAPie.removeAll();
                ComboAPie.addItem("Distancia");
                ComboAPie.addItem("Gasolina");
                ComboAPie.addItem("Gasolina y Distancia");

            } else {
                ComboAPie.setVisible(true);
                ImageIcon piee = new ImageIcon("auto2.png");
                imagTransporte.setIcon(new ImageIcon(piee.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH)));
                ComboAPie.addItem("Distancia");
                ComboAPie.addItem("Desgaste Fisico");
                ComboAPie.addItem("Distancia y Desgaste F.");

            }
        }

    }

    public void LlenarPuntosRuta() {
        puntosRuta.removeAllItems();
        if (recorrido.size() > 0) {
            if (recorrido.get(comboDestino.getSelectedIndex()).getVertices() != null) {
                for (int i = 0; i < recorrido.get(comboDestino.getSelectedIndex()).getVertices().size(); i++) {
                    puntosRuta.addItem(recorrido.get(comboDestino.getSelectedIndex()).getVertices().get(i).getNombre());

                }
                lblDist.setText(String.valueOf(recorrido.get(comboDestino.getSelectedIndex()).getPeso()));
            }
        }

    }

    int buscarIndice(ArrayList<Vertice> ver, String nombre) {
        for (int i = 0; i < ver.size(); i++) {
            if (nombre.equals(ver.get(i).getNombre())) {
                return i;
            }
        }
        return 0;
    }
    
    public int obtenerIndiceLista(Recorrido recorrido ){
        
        for (int i = 0; i < listaRecorridosFab.Size(); i++) {
            if(listaRecorridosFab.obtenerObjeto(i).equals(recorrido)){
                return i;
            }
        }
        return -1;
    }
    
    public void ingresarCamino(Recorrido recorrido){
        if(obtenerIndiceLista(recorrido )<0){
            listaRecorridosFab.insertarFinal(recorrido);
            System.out.println( listaRecorridosFab.Size()+ "TAM DE LA LISTA DE FAVORITOS");
        }else{
            aumentarNumeroRecorrido( recorrido);
        }
    }
    
    public void ingresarCaminos(Recorrido recorrido){
            ingresarCamino(recorrido);
        
    }
    
    public void aumentarNumeroRecorrido(Recorrido recorrido){
        int indice = obtenerIndiceLista(recorrido );
        int numero =listaRecorridosFab.obtenerNumero(indice);
        listaRecorridosFab.obtenerNodo(indice).setNumeroUsos(numero+1);
    }

    public void llenarRtuas(Arbol arbol, ArrayList<Recorrido> recorr) {
        arbol.dibujarArbol(arbol.getRaiz());
        comboDestino.removeAllItems();
        arbol.RecorrerArbol(arbol.getRaiz());
        recorrido = recorr;
        System.out.println("Arbol TAM" + recorrido.size());
//        System.out.println("Raiz arbil " + arbol.getRaiz().claves[0].getId());

        for (int i = 0; i < recorrido.size(); i++) {
            mejorRuta.setText(Integer.toString(recorrido.get(0).getId()));
            comboDestino.addItem(Integer.toString(recorrido.get(i).getId()));
            System.out.println(recorrido.get(i).getPeso());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboAPie;
    private javax.swing.JComboBox<String> ComboDestino3;
    private javax.swing.JComboBox<String> ComboOrigen;
    private javax.swing.JPanel arbolPanel;
    private javax.swing.JButton btnBuscarRutas;
    private javax.swing.JButton btnIr;
    private javax.swing.JComboBox<String> comboDestino;
    private javax.swing.JPanel comboOrigen;
    private javax.swing.JButton guardaImagen;
    private javax.swing.JLabel idFav;
    private javax.swing.JLabel imagTransporte;
    private javax.swing.JPanel imagenPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblDist;
    private javax.swing.JLabel mejorRuta;
    private javax.swing.JPanel panelIrRutas;
    private javax.swing.JComboBox<String> puntosRuta;
    private javax.swing.JLabel tipoTransporte;
    // End of variables declaration//GEN-END:variables
}
