/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Backend.Arbol;
import Backend.Dato;
import Backend.Grafos.Grafos;
import Backend.Grafos.Vertice;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author astridmc
 */
public class Ventana1 extends javax.swing.JPanel {

    Grafos grafo = new Grafos();
    public static String medio = null;
    ArrayList<Dato> datos = null;

    /**
     * Creates new form Ventana1
     *
     * @param datos1
     */
    public Ventana1(ArrayList<Dato> datos1) {
        initComponents();
        datos = datos1;
        panelIrRutas.setVisible(false);

        LlenarMedio();
        grafo.InsertarVertices(datos);
        LlenarLugares();
        insertarImagen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboOrigen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ComboOrigen = new javax.swing.JComboBox<>();
        btnBuscarRutas = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        ComboAPie = new javax.swing.JComboBox<>();
        ComboDestino3 = new javax.swing.JComboBox<>();
        imagenPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        tipoTransporte = new javax.swing.JLabel();
        imagTransporte = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        panelIrRutas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mejorRuta = new javax.swing.JLabel();
        comboDestino = new javax.swing.JComboBox<>();
        btnIr = new javax.swing.JButton();
        puntosRuta = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(202, 230, 253));

        comboOrigen.setBackground(new java.awt.Color(1, 60, 66));
        comboOrigen.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(254, 254, 254), new java.awt.Color(254, 254, 254)));
        comboOrigen.setForeground(new java.awt.Color(254, 254, 254));

        jLabel1.setFont(new java.awt.Font("URW Chancery L", 1, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Escoja el Origen:");

        jLabel2.setFont(new java.awt.Font("URW Chancery L", 1, 27)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Escoja el Destino:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setAlignmentY(1.0F);

        ComboOrigen.setFont(new java.awt.Font("URW Bookman L", 3, 20)); // NOI18N
        ComboOrigen.setForeground(new java.awt.Color(1, 1, 1));
        ComboOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboOrigenActionPerformed(evt);
            }
        });

        btnBuscarRutas.setFont(new java.awt.Font("URW Bookman L", 3, 18)); // NOI18N
        btnBuscarRutas.setForeground(new java.awt.Color(0, 132, 111));
        btnBuscarRutas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Imagenes/RutasPopulares.png"))); // NOI18N
        btnBuscarRutas.setText("BUSCAR RUTAS");
        btnBuscarRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRutasActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("URW Chancery L", 1, 27)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Buscar Rutas en Base A:");

        ComboAPie.setFont(new java.awt.Font("URW Bookman L", 3, 20)); // NOI18N
        ComboAPie.setForeground(new java.awt.Color(1, 1, 1));
        ComboAPie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboAPieActionPerformed(evt);
            }
        });

        ComboDestino3.setFont(new java.awt.Font("URW Bookman L", 3, 20)); // NOI18N
        ComboDestino3.setForeground(new java.awt.Color(1, 1, 1));
        ComboDestino3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout comboOrigenLayout = new javax.swing.GroupLayout(comboOrigen);
        comboOrigen.setLayout(comboOrigenLayout);
        comboOrigenLayout.setHorizontalGroup(
            comboOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comboOrigenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(comboOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comboOrigenLayout.createSequentialGroup()
                        .addGroup(comboOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(comboOrigenLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comboOrigenLayout.createSequentialGroup()
                                .addComponent(ComboOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(comboOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(comboOrigenLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                                .addComponent(ComboDestino3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))
                            .addGroup(comboOrigenLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(comboOrigenLayout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(ComboAPie, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarRutas, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(comboOrigenLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator2)
        );
        comboOrigenLayout.setVerticalGroup(
            comboOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comboOrigenLayout.createSequentialGroup()
                .addGroup(comboOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(comboOrigenLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comboOrigenLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ComboDestino3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(comboOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comboOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addComponent(btnBuscarRutas))
                    .addComponent(ComboAPie, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        imagenPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.black));
        imagenPanel.setMinimumSize(new java.awt.Dimension(50, 50));
        imagenPanel.setOpaque(false);
        imagenPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                imagenPanelComponentResized(evt);
            }
        });

        javax.swing.GroupLayout imagenPanelLayout = new javax.swing.GroupLayout(imagenPanel);
        imagenPanel.setLayout(imagenPanelLayout);
        imagenPanelLayout.setHorizontalGroup(
            imagenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        imagenPanelLayout.setVerticalGroup(
            imagenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(18, 55, 71));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tipoTransporte.setFont(new java.awt.Font("URW Chancery L", 3, 30)); // NOI18N
        tipoTransporte.setForeground(new java.awt.Color(254, 254, 254));
        tipoTransporte.setText("TRANSPORTE");

        imagTransporte.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tipoTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imagTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(imagTransporte, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(tipoTransporte, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)))
        );

        jPanel5.setBackground(new java.awt.Color(68, 232, 187));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.black));

        panelIrRutas.setBackground(new java.awt.Color(68, 232, 187));
        panelIrRutas.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, null));

        jLabel3.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(1, 1, 1));
        jLabel3.setText("La Mejor Ruta Es:");

        jLabel4.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(22, 0, 0));
        jLabel4.setText("Las Rutas posibles son:");

        mejorRuta.setFont(new java.awt.Font("URW Bookman L", 1, 18)); // NOI18N
        mejorRuta.setForeground(new java.awt.Color(132, 0, 0));
        mejorRuta.setText("Mejor Ruta");

        comboDestino.setFont(new java.awt.Font("URW Bookman L", 3, 20)); // NOI18N
        comboDestino.setForeground(new java.awt.Color(1, 1, 1));
        comboDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDestinoActionPerformed(evt);
            }
        });

        btnIr.setFont(new java.awt.Font("URW Bookman L", 3, 18)); // NOI18N
        btnIr.setForeground(new java.awt.Color(0, 132, 111));
        btnIr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Imagenes/localizar.png"))); // NOI18N
        btnIr.setText("  Ir");
        btnIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrActionPerformed(evt);
            }
        });

        puntosRuta.setFont(new java.awt.Font("URW Bookman L", 3, 20)); // NOI18N
        puntosRuta.setForeground(new java.awt.Color(1, 1, 1));
        puntosRuta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setFont(new java.awt.Font("URW Bookman L", 0, 16)); // NOI18N
        jLabel8.setText("Escoja el punto al que  ");

        jLabel9.setFont(new java.awt.Font("URW Bookman L", 0, 16)); // NOI18N
        jLabel9.setText("se mueve");

        javax.swing.GroupLayout panelIrRutasLayout = new javax.swing.GroupLayout(panelIrRutas);
        panelIrRutas.setLayout(panelIrRutasLayout);
        panelIrRutasLayout.setHorizontalGroup(
            panelIrRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIrRutasLayout.createSequentialGroup()
                .addGroup(panelIrRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIrRutasLayout.createSequentialGroup()
                        .addGroup(panelIrRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelIrRutasLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelIrRutasLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelIrRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(puntosRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIrRutasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(comboDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(panelIrRutasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIrRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIrRutasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelIrRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIrRutasLayout.createSequentialGroup()
                                .addComponent(mejorRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIrRutasLayout.createSequentialGroup()
                                .addComponent(btnIr, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54))))
                    .addGroup(panelIrRutasLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelIrRutasLayout.setVerticalGroup(
            panelIrRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIrRutasLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mejorRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(puntosRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIr))
        );

        btnIr.getAccessibleContext().setAccessibleName("IR");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelIrRutas, javax.swing.GroupLayout.PREFERRED_SIZE, 237, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelIrRutas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(191, 15, 11));
        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(254, 254, 254));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(comboOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imagenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imagenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ComboOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboOrigenActionPerformed

    private void btnBuscarRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRutasActionPerformed
        Arbol arbol = new Arbol();
        Vertice verticeOrigen = grafo.getVertices().get(ComboOrigen.getSelectedIndex());
        Vertice verticeDestino = grafo.getVertices().get(ComboDestino3.getSelectedIndex());
        if("A Pie".equals(medio)){
            int opcion =   ComboAPie.getSelectedIndex();
            grafo.setCaminosRecorridos();
            grafo.CrearRecorridos(verticeOrigen ,  verticeDestino );
            arbol.cerearArbol(grafo.CalcularMenorRecorrido(opcion, false));
        }else{
            int opcion =   ComboAPie.getSelectedIndex();
            grafo.setCaminosRecorridos();
            grafo.CrearRecorridos( verticeOrigen , verticeDestino);
            arbol.cerearArbol(grafo.CalcularMenorRecorrido(opcion, true));
        }
        
        panelIrRutas.setVisible(true);
    }//GEN-LAST:event_btnBuscarRutasActionPerformed

    private void btnIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIrActionPerformed

    private void ComboAPieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboAPieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboAPieActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDestinoActionPerformed

    private void imagenPanelComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_imagenPanelComponentResized
        try {
            if (imagenPanel.getComponents().length > 0) {
                imagen.setBounds(0, 0, imagenPanel.getWidth(), imagenPanel.getHeight());
                imagen.setIcon(new ImageIcon(portada.getImage().getScaledInstance(imagenPanel.getWidth(), imagenPanel.getHeight(), Image.SCALE_SMOOTH)));
                imagenPanel.remove(0);
                imagenPanel.add(imagen);
                System.out.println(imagenPanel.getComponent(0).getName());
            }
        } catch (Exception e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_imagenPanelComponentResized
    String fondo = "grafo.png";
    JLabel imagen = new JLabel();
    ImageIcon portada;

    public void insertarImagen() {
        try {
            portada = new ImageIcon(fondo);
            imagenPanel.setVisible(false);
            imagen.setBounds(0, 0, imagenPanel.getWidth(), imagenPanel.getHeight());
            if (imagenPanel.getWidth() > 0 && imagenPanel.getHeight() > 0) {
                System.out.println("ooooooo");
                imagen.setIcon(new ImageIcon(portada.getImage().getScaledInstance(imagenPanel.getWidth(), imagenPanel.getHeight(), Image.SCALE_SMOOTH)));
            } else {
                imagen.setIcon(new ImageIcon(portada.getImage().getScaledInstance(3276, 3276, Image.SCALE_SMOOTH)));
            }
            imagenPanel.add(imagen);
            imagenPanel.repaint();
            System.out.println("pintadoooo");
            imagenPanel.setVisible(true);
        } catch (Exception e) {
            System.out.println(e+"errrr");
        }

    }

    public void LlenarLugares() {
        ComboOrigen.removeAllItems();
        ComboDestino3.removeAllItems();
        for (int i = 0; i < grafo.getVertices().size(); i++) {
            String id = Integer.toString(datos.get(i).getId());

            ComboOrigen.addItem(grafo.getVertices().get(i).getNombre());
            ComboDestino3.addItem(grafo.getVertices().get(i).getNombre());
        }
        
        
    }

    public void LlenarMedio() {
        if (medio != null) {
            tipoTransporte.setText(medio);
            if ("A Pie".equals(medio)) {
                ComboAPie.setVisible(true);
                ImageIcon piee = new ImageIcon("peaton2.png");
                imagTransporte.setIcon(new ImageIcon(piee.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH)));
                ComboAPie.removeAll();
                ComboAPie.addItem("Distancia");
                ComboAPie.addItem("Gasolina");
                ComboAPie.addItem("Gasolina y Distancia");

            } else {
                ComboAPie.setVisible(true);
                ImageIcon piee = new ImageIcon("auto2.png");
                imagTransporte.setIcon(new ImageIcon(piee.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH)));
                ComboAPie.addItem("Distancia");
                ComboAPie.addItem("Desgaste Fisico");
                ComboAPie.addItem("Distancia y Desgaste F.");
                
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboAPie;
    private javax.swing.JComboBox<String> ComboDestino3;
    private javax.swing.JComboBox<String> ComboOrigen;
    private javax.swing.JButton btnBuscarRutas;
    private javax.swing.JButton btnIr;
    private javax.swing.JComboBox<String> comboDestino;
    private javax.swing.JPanel comboOrigen;
    private javax.swing.JLabel imagTransporte;
    private javax.swing.JPanel imagenPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel mejorRuta;
    private javax.swing.JPanel panelIrRutas;
    private javax.swing.JComboBox<String> puntosRuta;
    private javax.swing.JLabel tipoTransporte;
    // End of variables declaration//GEN-END:variables
}
